<?php
header("Access-Control-Allow-Origin: *");
header('Access-Control-Allow-Headers: Content-Type');
$rest_json = file_get_contents("php://input"); // JSONでPOSTされたデータを取り出す
$_POST = json_decode($rest_json, true); // JSON文字列をデコード
$command_post="python3 set_profilesearchsetting1.py " //pythonに引数を渡す
.$_POST['UUID']." "
.$_POST['PSGender0']." "
.$_POST['PSGender1']." "
.$_POST['PSGender2']." "
.$_POST['PSGender3']." "
.$_POST['PSGender4']." "
.$_POST['PSGender5']." "
.$_POST['PSGender6']." "
.$_POST['PSGender7']." "
.$_POST['PSAge0']." "
.$_POST['PSAge1']." "
.$_POST['PSAge2']." "
.$_POST['PSAge3']." "
.$_POST['PSAge4']." "
.$_POST['PSAge5']." "
.$_POST['PSAge6']." "
.$_POST['PSAge7']." "
.$_POST['PSAge8']." "
.$_POST['PSAge9']." "
.$_POST['PSAge10']." "
.$_POST['PSAge11']." "
.$_POST['PSAge12']." "
.$_POST['PSAge13']." "
.$_POST['PSAge14']." "
.$_POST['PSAge15']." "
.$_POST['PSAge16']." "
.$_POST['PSAge17']." "
.$_POST['PSProfilePicture0']." "
.$_POST['PSProfilePicture1']." "
.$_POST['PSProfilePicture2']." "
.$_POST['PSProfileMessage0']." "
.$_POST['PSProfileMessage1']." "
.$_POST['PSProfileMessage2']." "
.$_POST['PSHeight0']." "
.$_POST['PSHeight1']." "
.$_POST['PSHeight2']." "
.$_POST['PSHeight3']." "
.$_POST['PSHeight4']." "
.$_POST['PSHeight5']." "
.$_POST['PSHeight6']." "
.$_POST['PSHeight7']." "
.$_POST['PSHeight8']." "
.$_POST['PSHeight9']." "
.$_POST['PSStyle0']." "
.$_POST['PSStyle1']." "
.$_POST['PSStyle2']." "
.$_POST['PSStyle3']." "
.$_POST['PSStyle4']." "
.$_POST['PSStyle5']." "
.$_POST['PSStyle6']." "
.$_POST['PSStyle7']." "
.$_POST['PSStyle8']." "
.$_POST['PSStyle9']." "
.$_POST['PSLooks0']." "
.$_POST['PSLooks1']." "
.$_POST['PSLooks2']." "
.$_POST['PSLooks3']." "
.$_POST['PSLooks4']." "
.$_POST['PSLooks5']." "
.$_POST['PSLooks6']." "
.$_POST['PSLooks7']." "
.$_POST['PSLooks8']." "
.$_POST['PSLooks9']." "
.$_POST['PSCup0']." "
.$_POST['PSCup1']." "
.$_POST['PSCup2']." "
.$_POST['PSCup3']." "
.$_POST['PSCup4']." "
.$_POST['PSCup5']." "
.$_POST['PSCup6']." "
.$_POST['PSCup7']." "
.$_POST['PSCup8']." "
.$_POST['PSCup9']." "
.$_POST['PSBloodType0']." "
.$_POST['PSBloodType1']." "
.$_POST['PSBloodType2']." "
.$_POST['PSBloodType3']." "
.$_POST['PSBloodType4']." "
.$_POST['PSJob0']." "
.$_POST['PSJob1']." "
.$_POST['PSJob2']." "
.$_POST['PSJob3']." "
.$_POST['PSJob4']." "
.$_POST['PSJob5']." "
.$_POST['PSJob6']." "
.$_POST['PSJob7']." "
.$_POST['PSJob8']." "
.$_POST['PSJob9']." "
.$_POST['PSJob10']." "
.$_POST['PSJob11']." "
.$_POST['PSJob12']." "
.$_POST['PSJob13']." "
.$_POST['PSJob14']." "
.$_POST['PSJob15']." "
.$_POST['PSJob16']." "
.$_POST['PSJob17']." "
.$_POST['PSJob18']." "
.$_POST['PSJob19']." "
.$_POST['PSJob20']." "
.$_POST['PSJob21']." "
.$_POST['PSJob22']." "
.$_POST['PSJob23']." "
.$_POST['PSJob24']." "
.$_POST['PSJob25']." "
.$_POST['PSJob26']." "
.$_POST['PSEduBack0']." "
.$_POST['PSEduBack1']." "
.$_POST['PSEduBack2']." "
.$_POST['PSEduBack3']." "
.$_POST['PSEduBack4']." "
.$_POST['PSEduBack5']." "
.$_POST['PSZodiac0']." "
.$_POST['PSZodiac1']." "
.$_POST['PSZodiac2']." "
.$_POST['PSZodiac3']." "
.$_POST['PSZodiac4']." "
.$_POST['PSZodiac5']." "
.$_POST['PSZodiac6']." "
.$_POST['PSZodiac7']." "
.$_POST['PSZodiac8']." "
.$_POST['PSZodiac9']." "
.$_POST['PSZodiac10']." "
.$_POST['PSZodiac11']." "
.$_POST['PSZodiac12']." "
.$_POST['PSMarriageStatus0']." "
.$_POST['PSMarriageStatus1']." "
.$_POST['PSMarriageStatus2']." "
.$_POST['PSMarriageStatus3']." "
.$_POST['PSMarriageStatus4']." "
.$_POST['PSMarriageStatus5']." "
.$_POST['PSMarriageStatus6']." "
.$_POST['PSKids0']." "
.$_POST['PSKids1']." "
.$_POST['PSKids2']." "
.$_POST['PSKids3']." "
.$_POST['PSTabacco0']." "
.$_POST['PSTabacco1']." "
.$_POST['PSTabacco2']." "
.$_POST['PSTabacco3']." "
.$_POST['PSTabacco4']." "
.$_POST['PSAlchole0']." "
.$_POST['PSAlchole1']." "
.$_POST['PSAlchole2']." "
.$_POST['PSAlchole3']." "
.$_POST['PSCar0']." "
.$_POST['PSCar1']." "
.$_POST['PSCar2']." "
.$_POST['PSInterest0']." "
.$_POST['PSInterest1']." "
.$_POST['PSInterest2']." "
.$_POST['PSInterest3']." "
.$_POST['PSInterest4']." "
.$_POST['PSInterest5']." "
.$_POST['PSInterest6']." "
.$_POST['PSInterest7']." "
.$_POST['PSInterest8']." "
.$_POST['PSInterest9']." "
.$_POST['PSInterest10']." "
.$_POST['PSInterest11']." "
.$_POST['PSInterest12']." "
.$_POST['PSInterest13']." "
.$_POST['PSInterest14']." "
.$_POST['PSInterest15']." "
.$_POST['PSInterest16']." "
.$_POST['PSInterest17']." "
.$_POST['PSInterest18']." "
.$_POST['PSInterest19']." "
.$_POST['PSInterest20']." "
.$_POST['PSInterest21']." "
.$_POST['PSInterest22']." "
.$_POST['PSInterest23']." "
.$_POST['PSInterest24']." "
.$_POST['PSInterest25']." "
.$_POST['PSInterest26']." "
.$_POST['PSInterest27']." "
.$_POST['PSInterest28']." "
.$_POST['PSPersonality0']." "
.$_POST['PSPersonality1']." "
.$_POST['PSPersonality2']." "
.$_POST['PSPersonality3']." "
.$_POST['PSPersonality4']." "
.$_POST['PSPersonality5']." "
.$_POST['PSPersonality6']." "
.$_POST['PSPersonality7']." "
.$_POST['PSPersonality8']." "
.$_POST['PSPersonality9']." "
.$_POST['PSPersonality10']." "
.$_POST['PSPersonality11']." "
.$_POST['PSPersonality12']." "
.$_POST['PSPersonality13']." "
.$_POST['PSPersonality14']." "
.$_POST['PSPersonality15']." "
.$_POST['PSPersonality16']." "
.$_POST['PSPersonality17']." "
.$_POST['PSPersonality18']." "
.$_POST['PSPersonality19']." "
.$_POST['PSPersonality20']." "
.$_POST['PSPersonality21']." "
.$_POST['PSPersonality22']." "
.$_POST['PSPersonality23']." "
.$_POST['PSPersonality24']." "
.$_POST['PSPersonality25']." "
.$_POST['PSPersonality26']." "
.$_POST['PSPersonality27']." "
.$_POST['PSPersonality28']." "
.$_POST['PSPersonality29']." "
.$_POST['PSPersonality30']." "
.$_POST['PSPersonality31']." "
.$_POST['PSPersonality32']." "
.$_POST['PSPersonality33']." "
.$_POST['PSPersonality34']." "
.$_POST['PSPersonality35']." "
.$_POST['PSPersonality36']." "
.$_POST['PSPersonality37']." "
.$_POST['PSPersonality38']." "
.$_POST['PSPersonality39']." "
.$_POST['PSPersonality40']." "
.$_POST['PSPersonality41']." "
.$_POST['PSPersonality42']." "
.$_POST['PSPersonality43']." "
.$_POST['PSPersonality44']." "
.$_POST['PSPersonality45']." "
.$_POST['PSPersonality46']." "
.$_POST['PSAnnuIncome0']." "
.$_POST['PSAnnuIncome1']." "
.$_POST['PSAnnuIncome2']." "
.$_POST['PSAnnuIncome3']." "
.$_POST['PSAnnuIncome4']." "
.$_POST['PSAnnuIncome5']." "
.$_POST['PSAnnuIncome6']." "
.$_POST['PSAnnuIncome7']." "
.$_POST['PSAnnuIncome8']." "
.$_POST['PSAnnuIncome9']." "
.$_POST['PSAnnuIncome10']." "
.$_POST['PSCute0']." "
.$_POST['PSCute1']." "
.$_POST['PSCute2']." "
.$_POST['PSCute3']." "
.$_POST['PSCute4']." "
.$_POST['PSCute5']." "
.$_POST['PSSexy0']." "
.$_POST['PSSexy1']." "
.$_POST['PSSexy2']." "
.$_POST['PSSexy3']." "
.$_POST['PSSexy4']." "
.$_POST['PSSexy5']." "
.$_POST['PSKindness0']." "
.$_POST['PSKindness1']." "
.$_POST['PSKindness2']." "
.$_POST['PSKindness3']." "
.$_POST['PSKindness4']." "
.$_POST['PSKindness5']." "
.$_POST['PSSmartness0']." "
.$_POST['PSSmartness1']." "
.$_POST['PSSmartness2']." "
.$_POST['PSSmartness3']." "
.$_POST['PSSmartness4']." "
.$_POST['PSSmartness5']." "
.$_POST['PSNeatness0']." "
.$_POST['PSNeatness1']." "
.$_POST['PSNeatness2']." "
.$_POST['PSNeatness3']." "
.$_POST['PSNeatness4']." "
.$_POST['PSNeatness5']." "
.$_POST['PSFashionable0']." "
.$_POST['PSFashionable1']." "
.$_POST['PSFashionable2']." "
.$_POST['PSFashionable3']." "
.$_POST['PSFashionable4']." "
.$_POST['PSFashionable5']." "
.$_POST['PSBrightness0']." "
.$_POST['PSBrightness1']." "
.$_POST['PSBrightness2']." "
.$_POST['PSBrightness3']." "
.$_POST['PSBrightness4']." "
.$_POST['PSBrightness5']." "
.$_POST['PSElegance0']." "
.$_POST['PSElegance1']." "
.$_POST['PSElegance2']." "
.$_POST['PSElegance3']." "
.$_POST['PSElegance4']." "
.$_POST['PSElegance5'];
exec($command_post, $output); //python実行と、返り数受け取り

echo json_encode(
  [
    "_POST" => $_POST,
    // "result" => $output,
    "result" => $output,
  ]
);
// echo json_encode(
//   [
//     "PSGender" => $_POST['PSGender'],
//     // "json_enc_PSGender" => json_encode($_POST['PSGender']),
//     // "json_enc_PSGender_array" => json_encode(array($_POST['PSGender'])),
//     // "json_enc_dec_PSGender" => json_encode(array(json_decode($_POST['PSGender'], true))),
//     "json_dec_PSGender" => json_decode($_POST['PSGender'], true),
//     // "json_enc_dec_PSGender" => json_encode(json_decode($_POST['PSGender'], true)),
//     // "result" => $output,
//     "result" => "test",
//     // "result" => $_POST['PSProfileMessage'],
//   ]
// );

// // pythonからの返り数のうち、SQLのヘッダーの受け取りと、文字列から配列変換(pythonの出力1行目)
// $output[0]=trim($output[0],"\"['");
// $output[0]=trim($output[0],"']\"");
// $output0=explode("', '",$output[0]);

// $output2=array();
// $it = 0;

// // pythonからの返り数のうち、SQLの受け取りと、文字列から配列変換(pythonの残りの行全て)
// foreach ($output as $value) {
//     $value=trim($value,"\"[");
//     $value=trim($value,"]\"");
//     $value=str_replace("'",'',$value);
//     $value1=explode(", ",$value);
//     $output1 = array_combine($output0,$value1);
//     $output2 = $output2 + array("$it" => $output1);
//     $it = $it + 1;
// }
// // 配列1行目の削除と、配列詰め
// unset($output2[0]);
// $output2 = array_values($output2);

// //配列のJSON変換と、echoでのサーバーサイド出力。
// if(empty($_POST['email']))
// {
//   echo json_encode(
//       [
//         "result" => "EmailAdded",
//       ]
//     );
// }
// else
// {
//   echo json_encode(
//       [
//         "result" => "EmailExist",
//       ]
//     );
// }